name: Release
on:
  workflow_dispatch: {}
  push:
    tags:
    - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-cli:
    strategy:
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          subtarget: x86_64-unknown-linux-gnu
          runs-on: ubuntu-24.04
        - target: x86_64-unknown-linux-gnu.2.31
          subtarget: x86_64-unknown-linux-gnu
          runs-on: ubuntu-24.04
        - target: aarch64-unknown-linux-gnu
          subtarget: aarch64-unknown-linux-gnu
          runs-on: ubuntu-24.04-arm
        - target: aarch64-unknown-linux-gnu.2.31
          subtarget: aarch64-unknown-linux-gnu
          runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.subtarget }}

      - name: Install cargo-zigbuild
        run: cargo install --locked cargo-zigbuild
      
      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          cargo zigbuild --release --target ${{ matrix.target }}
          arch="${{ matrix.target }}"
          arch="${arch//./-}"
          mkdir bin
          mv target/${{ matrix.subtarget }}/release/rusbee "bin/rusbee-${arch}"

      - uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.target }}
          if-no-files-found: error
          path: bin/*

  release-cli:
    runs-on: ubuntu-24.04
    needs: 
    - build-cli
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Binary Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: binaries-*
          path: bin

      - name: Calculate checksums
        run: |
          for file in bin/*; do
            shasum -a 256 "$file" >> checksums.txt
          done

          mv checksums.txt bin/checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            bin/*
